# Generated by Django 2.0.4 on 2018-04-06 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('name', models.CharField(max_length=250, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscribe.Location')),
            ],
        ),
    ]
